#!/bin/bash
# Fix DB-V3 with ALL 147 DOT Columns + Insurance Data
echo "🔧 FIXING DB-V3 WITH COMPLETE 147 DOT COLUMNS"
echo "=============================================="

INSURANCE_FILE="/var/www/vanguard/actpendins_allwithhistory.3.txt"
DOT_DB="/var/www/vanguard/DB-advanced.db"
TARGET_DB="/var/www/vanguard/DB-V3.db"

# Remove and recreate with FULL schema
rm -f "$TARGET_DB"

echo "🔨 Creating DB-V3 with COMPLETE DOT schema..."

# Create the complete structure
sqlite3 "$TARGET_DB" <<EOF
-- Complete carriers table with ALL 147 DOT columns
CREATE TABLE carriers (
    -- Core DOT Columns
    MCS150_DATE TEXT,
    ADD_DATE TEXT,
    STATUS_CODE TEXT,
    DOT_NUMBER INTEGER PRIMARY KEY,
    DUN_BRADSTREET_NO TEXT,
    PHY_OMC_REGION TEXT,
    SAFETY_INV_TERR TEXT,
    CARRIER_OPERATION TEXT,
    BUSINESS_ORG_ID TEXT,
    MCS150_MILEAGE TEXT,
    MCS150_MILEAGE_YEAR TEXT,
    MCS151_MILEAGE TEXT,
    TOTAL_CARS TEXT,
    MCS150_UPDATE_CODE_ID TEXT,
    PRIOR_REVOKE_FLAG TEXT,
    PRIOR_REVOKE_DOT_NUMBER TEXT,

    -- Contact Information
    PHONE TEXT,
    FAX TEXT,
    CELL_PHONE TEXT,
    COMPANY_OFFICER_1 TEXT,
    COMPANY_OFFICER_2 TEXT,
    EMAIL_ADDRESS TEXT,

    -- Business Information
    BUSINESS_ORG_DESC TEXT,
    LEGAL_NAME TEXT,
    DBA_NAME TEXT,
    CLASSDEF TEXT,

    -- Fleet Information
    TRUCK_UNITS TEXT,
    POWER_UNITS TEXT,
    BUS_UNITS TEXT,
    FLEETSIZE TEXT,

    -- Address Information
    PHY_STREET TEXT,
    PHY_CITY TEXT,
    PHY_COUNTRY TEXT,
    PHY_STATE TEXT,
    PHY_ZIP TEXT,
    PHY_CNTY TEXT,
    CARRIER_MAILING_STREET TEXT,
    CARRIER_MAILING_STATE TEXT,
    CARRIER_MAILING_CITY TEXT,
    CARRIER_MAILING_COUNTRY TEXT,
    CARRIER_MAILING_ZIP TEXT,
    CARRIER_MAILING_CNTY TEXT,
    CARRIER_MAILING_UND_DATE TEXT,

    -- Safety Information
    REVIEW_ID TEXT,
    RECORDABLE_CRASH_RATE TEXT,
    REVIEW_TYPE TEXT,
    REVIEW_DATE TEXT,
    SAFETY_RATING TEXT,
    SAFETY_RATING_DATE TEXT,

    -- Cargo Types (CRGO fields)
    CRGO_GENFREIGHT TEXT,
    CRGO_HOUSEHOLD TEXT,
    CRGO_METALSHEET TEXT,
    CRGO_MOTOVEH TEXT,
    CRGO_DRIVETOW TEXT,
    CRGO_LOGPOLE TEXT,
    CRGO_BLDGMAT TEXT,
    CRGO_MOBILEHOME TEXT,
    CRGO_MACHLRG TEXT,
    CRGO_PRODUCE TEXT,
    CRGO_LIQGAS TEXT,
    CRGO_INTERMODAL TEXT,
    CRGO_PASSENGERS TEXT,
    CRGO_OILFIELD TEXT,
    CRGO_LIVESTOCK TEXT,
    CRGO_GRAINFEED TEXT,
    CRGO_COALCOKE TEXT,
    CRGO_MEAT TEXT,
    CRGO_GARBAGE TEXT,
    CRGO_USMAIL TEXT,
    CRGO_CHEM TEXT,
    CRGO_DRYBULK TEXT,
    CRGO_COLDFOOD TEXT,
    CRGO_BEVERAGES TEXT,
    CRGO_PAPERPROD TEXT,
    CRGO_UTILITY TEXT,
    CRGO_FARMSUPP TEXT,
    CRGO_CONSTRUCT TEXT,
    CRGO_WATERWELL TEXT,
    CRGO_CARGOOTHR TEXT,
    CRGO_CARGOOTHR_DESC TEXT,

    -- Driver Information
    TOTAL_INTRASTATE_DRIVERS TEXT,
    INTERSTATE_BEYOND_100_MILES TEXT,
    INTERSTATE_WITHIN_100_MILES TEXT,
    INTRASTATE_BEYOND_100_MILES TEXT,
    INTRASTATE_WITHIN_100_MILES TEXT,
    TOTAL_CDL TEXT,
    TOTAL_DRIVERS TEXT,
    AVG_DRIVERS_LEASED_PER_MONTH TEXT,
    DRIVER_INTER_TOTAL TEXT,

    -- Additional Fields
    MAIL_NATIONALITY_INDICATOR TEXT,
    PHY_NATIONALITY_INDICATOR TEXT,
    PHY_BARRIO TEXT,
    MAIL_BARRIO TEXT,
    CARSHIP TEXT,
    DOCKET1PREFIX TEXT,
    DOCKET1 TEXT,
    DOCKET2PREFIX TEXT,
    DOCKET2 TEXT,
    DOCKET3PREFIX TEXT,
    DOCKET3 TEXT,
    POINTNUM TEXT,
    MCSIPSTEP TEXT,
    MCSIPDATE TEXT,
    HM_Ind TEXT,
    UNDELIV_PHY TEXT,

    -- Equipment Owned
    OWNTRUCK TEXT,
    OWNTRACT TEXT,
    OWNTRAIL TEXT,
    OWNCOACH TEXT,
    OWNSCHOOL_1_8 TEXT,
    OWNSCHOOL_9_15 TEXT,
    OWNSCHOOL_16 TEXT,
    OWNBUS_16 TEXT,
    OWNVAN_1_8 TEXT,
    OWNVAN_9_15 TEXT,
    OWNLIMO_1_8 TEXT,
    OWNLIMO_9_15 TEXT,
    OWNLIMO_16 TEXT,

    -- Equipment Term Leased
    TRMTRUCK TEXT,
    TRMTRACT TEXT,
    TRMTRAIL TEXT,
    TRMCOACH TEXT,
    TRMSCHOOL_1_8 TEXT,
    TRMSCHOOL_9_15 TEXT,
    TRMSCHOOL_16 TEXT,
    TRMBUS_16 TEXT,
    TRMVAN_1_8 TEXT,
    TRMVAN_9_15 TEXT,
    TRMLIMO_1_8 TEXT,
    TRMLIMO_9_15 TEXT,
    TRMLIMO_16 TEXT,

    -- Equipment Trip Leased
    TRPTRUCK TEXT,
    TRPTRACT TEXT,
    TRPTRAIL TEXT,
    TRPCOACH TEXT,
    TRPSCHOOL_1_8 TEXT,
    TRPSCHOOL_9_15 TEXT,
    TRPSCHOOL_16 TEXT,
    TRPBUS_16 TEXT,
    TRPVAN_1_8 TEXT,
    TRPVAN_9_15 TEXT,
    TRPLIMO_1_8 TEXT,
    TRPLIMO_9_15 TEXT,
    TRPLIMO_16 TEXT,

    -- Status Codes
    DOCKET1_STATUS_CODE TEXT,
    DOCKET2_STATUS_CODE TEXT,
    DOCKET3_STATUS_CODE TEXT,

    -- Metadata
    CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_SOURCE TEXT DEFAULT 'DOT_INSURANCE_MERGED'
);

-- Insurance policies table (unchanged)
CREATE TABLE insurance_policies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    DOT_NUMBER INTEGER,
    MC_NUMBER TEXT,
    FORM_CODE TEXT,
    COVERAGE_TYPE TEXT,
    INSURANCE_COMPANY TEXT,
    POLICY_NUMBER TEXT,
    POLICY_EFFECTIVE_DATE TEXT,
    COVERAGE_AMOUNT TEXT,
    POLICY_END_DATE TEXT,
    POLICY_CANCELLATION_DATE TEXT,
    FOREIGN KEY (DOT_NUMBER) REFERENCES carriers(DOT_NUMBER)
);

-- Indexes
CREATE INDEX idx_carriers_dot ON carriers(DOT_NUMBER);
CREATE INDEX idx_carriers_state ON carriers(PHY_STATE);
CREATE INDEX idx_carriers_legal_name ON carriers(LEGAL_NAME);
CREATE INDEX idx_carriers_company_officer ON carriers(COMPANY_OFFICER_1);
CREATE INDEX idx_carriers_classdef ON carriers(CLASSDEF);
CREATE INDEX idx_policies_dot ON insurance_policies(DOT_NUMBER);
CREATE INDEX idx_policies_mc ON insurance_policies(MC_NUMBER);
EOF

echo "✅ Complete database structure created with ALL 147+ DOT columns"

echo ""
echo "📊 Step 1: Import insurance data..."

sqlite3 "$TARGET_DB" <<EOF
CREATE TEMP TABLE insurance_raw (
    MC_NUMBER TEXT,
    DOT_NUMBER INTEGER,
    FORM_CODE TEXT,
    COVERAGE_TYPE TEXT,
    INSURANCE_COMPANY TEXT,
    POLICY_NUMBER TEXT,
    POLICY_EFFECTIVE_DATE TEXT,
    UNKNOWN_FLAG TEXT,
    COVERAGE_AMOUNT TEXT,
    POLICY_END_DATE TEXT,
    POLICY_CANCELLATION_DATE TEXT
);

.mode csv
.separator ","
.import $INSURANCE_FILE insurance_raw

DELETE FROM insurance_raw WHERE DOT_NUMBER = 0 OR DOT_NUMBER IS NULL;

INSERT INTO insurance_policies (
    DOT_NUMBER, MC_NUMBER, FORM_CODE, COVERAGE_TYPE, INSURANCE_COMPANY,
    POLICY_NUMBER, POLICY_EFFECTIVE_DATE, COVERAGE_AMOUNT, POLICY_END_DATE, POLICY_CANCELLATION_DATE
)
SELECT
    DOT_NUMBER, MC_NUMBER, FORM_CODE, COVERAGE_TYPE, INSURANCE_COMPANY,
    POLICY_NUMBER, POLICY_EFFECTIVE_DATE, COVERAGE_AMOUNT, POLICY_END_DATE, POLICY_CANCELLATION_DATE
FROM insurance_raw;

SELECT 'Insurance policies imported: ' || COUNT(*) FROM insurance_policies;
EOF

echo "✅ Insurance data imported"

echo ""
echo "📊 Step 2: Import COMPLETE DOT data..."

sqlite3 "$TARGET_DB" <<EOF
ATTACH DATABASE '$DOT_DB' AS dot_db;

CREATE TEMP TABLE unique_dots AS
SELECT DISTINCT DOT_NUMBER FROM insurance_policies;

-- Import ALL columns from DOT database
INSERT INTO carriers (
    MCS150_DATE, ADD_DATE, STATUS_CODE, DOT_NUMBER, DUN_BRADSTREET_NO,
    PHY_OMC_REGION, SAFETY_INV_TERR, CARRIER_OPERATION, BUSINESS_ORG_ID, MCS150_MILEAGE,
    MCS150_MILEAGE_YEAR, MCS151_MILEAGE, TOTAL_CARS, MCS150_UPDATE_CODE_ID, PRIOR_REVOKE_FLAG,
    PRIOR_REVOKE_DOT_NUMBER, PHONE, FAX, CELL_PHONE, COMPANY_OFFICER_1,
    COMPANY_OFFICER_2, EMAIL_ADDRESS, BUSINESS_ORG_DESC, LEGAL_NAME, DBA_NAME,
    CLASSDEF, TRUCK_UNITS, POWER_UNITS, BUS_UNITS, FLEETSIZE,
    PHY_STREET, PHY_CITY, PHY_COUNTRY, PHY_STATE, PHY_ZIP,
    PHY_CNTY, CARRIER_MAILING_STREET, CARRIER_MAILING_STATE, CARRIER_MAILING_CITY, CARRIER_MAILING_COUNTRY,
    CARRIER_MAILING_ZIP, CARRIER_MAILING_CNTY, CARRIER_MAILING_UND_DATE, REVIEW_ID, RECORDABLE_CRASH_RATE,
    REVIEW_TYPE, REVIEW_DATE, SAFETY_RATING, SAFETY_RATING_DATE, CRGO_GENFREIGHT,
    CRGO_HOUSEHOLD, CRGO_METALSHEET, CRGO_MOTOVEH, CRGO_DRIVETOW, CRGO_LOGPOLE,
    CRGO_BLDGMAT, CRGO_MOBILEHOME, CRGO_MACHLRG, CRGO_PRODUCE, CRGO_LIQGAS,
    CRGO_INTERMODAL, CRGO_PASSENGERS, CRGO_OILFIELD, CRGO_LIVESTOCK, CRGO_GRAINFEED,
    CRGO_COALCOKE, CRGO_MEAT, CRGO_GARBAGE, CRGO_USMAIL, CRGO_CHEM,
    CRGO_DRYBULK, CRGO_COLDFOOD, CRGO_BEVERAGES, CRGO_PAPERPROD, CRGO_UTILITY,
    CRGO_FARMSUPP, CRGO_CONSTRUCT, CRGO_WATERWELL, CRGO_CARGOOTHR, CRGO_CARGOOTHR_DESC,
    TOTAL_INTRASTATE_DRIVERS, INTERSTATE_BEYOND_100_MILES, INTERSTATE_WITHIN_100_MILES, INTRASTATE_BEYOND_100_MILES, INTRASTATE_WITHIN_100_MILES,
    TOTAL_CDL, TOTAL_DRIVERS, AVG_DRIVERS_LEASED_PER_MONTH, DRIVER_INTER_TOTAL, MAIL_NATIONALITY_INDICATOR,
    PHY_NATIONALITY_INDICATOR, PHY_BARRIO, MAIL_BARRIO, CARSHIP, DOCKET1PREFIX,
    DOCKET1, DOCKET2PREFIX, DOCKET2, DOCKET3PREFIX, DOCKET3,
    POINTNUM, MCSIPSTEP, MCSIPDATE, HM_Ind, UNDELIV_PHY,
    OWNTRUCK, OWNTRACT, OWNTRAIL, OWNCOACH, OWNSCHOOL_1_8,
    OWNSCHOOL_9_15, OWNSCHOOL_16, OWNBUS_16, OWNVAN_1_8, OWNVAN_9_15,
    OWNLIMO_1_8, OWNLIMO_9_15, OWNLIMO_16, TRMTRUCK, TRMTRACT,
    TRMTRAIL, TRMCOACH, TRMSCHOOL_1_8, TRMSCHOOL_9_15, TRMSCHOOL_16,
    TRMBUS_16, TRMVAN_1_8, TRMVAN_9_15, TRMLIMO_1_8, TRMLIMO_9_15,
    TRMLIMO_16, TRPTRUCK, TRPTRACT, TRPTRAIL, TRPCOACH,
    TRPSCHOOL_1_8, TRPSCHOOL_9_15, TRPSCHOOL_16, TRPBUS_16, TRPVAN_1_8,
    TRPVAN_9_15, TRPLIMO_1_8, TRPLIMO_9_15, TRPLIMO_16, DOCKET1_STATUS_CODE,
    DOCKET2_STATUS_CODE, DOCKET3_STATUS_CODE
)
SELECT
    c.MCS150_DATE, c.ADD_DATE, c.STATUS_CODE, c.DOT_NUMBER, c.DUN_BRADSTREET_NO,
    c.PHY_OMC_REGION, c.SAFETY_INV_TERR, c.CARRIER_OPERATION, c.BUSINESS_ORG_ID, c.MCS150_MILEAGE,
    c.MCS150_MILEAGE_YEAR, c.MCS151_MILEAGE, c.TOTAL_CARS, c.MCS150_UPDATE_CODE_ID, c.PRIOR_REVOKE_FLAG,
    c.PRIOR_REVOKE_DOT_NUMBER, c.PHONE, c.FAX, c.CELL_PHONE, c.COMPANY_OFFICER_1,
    c.COMPANY_OFFICER_2, c.EMAIL_ADDRESS, c.BUSINESS_ORG_DESC, c.LEGAL_NAME, c.DBA_NAME,
    c.CLASSDEF, c.TRUCK_UNITS, c.POWER_UNITS, c.BUS_UNITS, c.FLEETSIZE,
    c.PHY_STREET, c.PHY_CITY, c.PHY_COUNTRY, c.PHY_STATE, c.PHY_ZIP,
    c.PHY_CNTY, c.CARRIER_MAILING_STREET, c.CARRIER_MAILING_STATE, c.CARRIER_MAILING_CITY, c.CARRIER_MAILING_COUNTRY,
    c.CARRIER_MAILING_ZIP, c.CARRIER_MAILING_CNTY, c.CARRIER_MAILING_UND_DATE, c.REVIEW_ID, c.RECORDABLE_CRASH_RATE,
    c.REVIEW_TYPE, c.REVIEW_DATE, c.SAFETY_RATING, c.SAFETY_RATING_DATE, c.CRGO_GENFREIGHT,
    c.CRGO_HOUSEHOLD, c.CRGO_METALSHEET, c.CRGO_MOTOVEH, c.CRGO_DRIVETOW, c.CRGO_LOGPOLE,
    c.CRGO_BLDGMAT, c.CRGO_MOBILEHOME, c.CRGO_MACHLRG, c.CRGO_PRODUCE, c.CRGO_LIQGAS,
    c.CRGO_INTERMODAL, c.CRGO_PASSENGERS, c.CRGO_OILFIELD, c.CRGO_LIVESTOCK, c.CRGO_GRAINFEED,
    c.CRGO_COALCOKE, c.CRGO_MEAT, c.CRGO_GARBAGE, c.CRGO_USMAIL, c.CRGO_CHEM,
    c.CRGO_DRYBULK, c.CRGO_COLDFOOD, c.CRGO_BEVERAGES, c.CRGO_PAPERPROD, c.CRGO_UTILITY,
    c.CRGO_FARMSUPP, c.CRGO_CONSTRUCT, c.CRGO_WATERWELL, c.CRGO_CARGOOTHR, c.CRGO_CARGOOTHR_DESC,
    c.TOTAL_INTRASTATE_DRIVERS, c.INTERSTATE_BEYOND_100_MILES, c.INTERSTATE_WITHIN_100_MILES, c.INTRASTATE_BEYOND_100_MILES, c.INTRASTATE_WITHIN_100_MILES,
    c.TOTAL_CDL, c.TOTAL_DRIVERS, c.AVG_DRIVERS_LEASED_PER_MONTH, c.DRIVER_INTER_TOTAL, c.MAIL_NATIONALITY_INDICATOR,
    c.PHY_NATIONALITY_INDICATOR, c.PHY_BARRIO, c.MAIL_BARRIO, c.CARSHIP, c.DOCKET1PREFIX,
    c.DOCKET1, c.DOCKET2PREFIX, c.DOCKET2, c.DOCKET3PREFIX, c.DOCKET3,
    c.POINTNUM, c.MCSIPSTEP, c.MCSIPDATE, c.HM_Ind, c.UNDELIV_PHY,
    c.OWNTRUCK, c.OWNTRACT, c.OWNTRAIL, c.OWNCOACH, c.OWNSCHOOL_1_8,
    c.OWNSCHOOL_9_15, c.OWNSCHOOL_16, c.OWNBUS_16, c.OWNVAN_1_8, c.OWNVAN_9_15,
    c.OWNLIMO_1_8, c.OWNLIMO_9_15, c.OWNLIMO_16, c.TRMTRUCK, c.TRMTRACT,
    c.TRMTRAIL, c.TRMCOACH, c.TRMSCHOOL_1_8, c.TRMSCHOOL_9_15, c.TRMSCHOOL_16,
    c.TRMBUS_16, c.TRMVAN_1_8, c.TRMVAN_9_15, c.TRMLIMO_1_8, c.TRMLIMO_9_15,
    c.TRMLIMO_16, c.TRPTRUCK, c.TRPTRACT, c.TRPTRAIL, c.TRPCOACH,
    c.TRPSCHOOL_1_8, c.TRPSCHOOL_9_15, c.TRPSCHOOL_16, c.TRPBUS_16, c.TRPVAN_1_8,
    c.TRPVAN_9_15, c.TRPLIMO_1_8, c.TRPLIMO_9_15, c.TRPLIMO_16, c.DOCKET1_STATUS_CODE,
    c.DOCKET2_STATUS_CODE, c.DOCKET3_STATUS_CODE
FROM dot_db.carriers c
INNER JOIN unique_dots u ON c.DOT_NUMBER = u.DOT_NUMBER;

SELECT 'Complete carriers imported: ' || COUNT(*) FROM carriers;
DETACH DATABASE dot_db;
EOF

echo "✅ Complete DOT data imported with ALL columns"

echo ""
echo "📊 DB-V3 COMPLETE Results:"
sqlite3 "$TARGET_DB" "
SELECT 'Total carriers with ALL columns: ' || COUNT(*) FROM carriers;
SELECT 'Total insurance policies: ' || COUNT(*) FROM insurance_policies;
"

echo ""
echo "🎯 DB-V3 COMPLETE FIX SUCCESSFUL!"
echo "📁 Database: $TARGET_DB"
ls -lh "$TARGET_DB"

echo ""
echo "✅ Now includes ALL requested columns:"
echo "   • COMPANY_OFFICER_1 ✅"
echo "   • CLASSDEF ✅"
echo "   • ALL CRGO cargo types ✅"
echo "   • All 147+ DOT columns ✅"