#!/bin/bash
# Merge Insurance History + DOT Data into DB-V3
echo "🔗 MERGING INSURANCE + DOT DATA INTO DB-V3"
echo "=========================================="

INSURANCE_FILE="/var/www/vanguard/actpendins_allwithhistory.3.txt"
DOT_DB="/var/www/vanguard/DB-advanced.db"
TARGET_DB="/var/www/vanguard/DB-V3.db"

echo "📊 Source files:"
echo "   Insurance: $(wc -l < $INSURANCE_FILE) records"
echo "   DOT DB: $(sqlite3 $DOT_DB "SELECT COUNT(*) FROM carriers;") records"

echo ""
echo "🔄 Step 1: Creating temporary insurance table..."

# Create temporary table and import insurance data
sqlite3 "$TARGET_DB" <<EOF
-- Create temporary insurance table
CREATE TEMP TABLE insurance_temp (
    MC_NUMBER TEXT,
    DOT_NUMBER INTEGER,
    FORM_CODE TEXT,
    COVERAGE_TYPE TEXT,
    INSURANCE_COMPANY TEXT,
    POLICY_NUMBER TEXT,
    POLICY_EFFECTIVE_DATE TEXT,
    UNKNOWN_FLAG TEXT,
    COVERAGE_AMOUNT TEXT,
    POLICY_END_DATE TEXT,
    POLICY_CANCELLATION_DATE TEXT
);

-- Import insurance data
.mode csv
.separator ","
.import $INSURANCE_FILE insurance_temp

-- Check import
SELECT 'Insurance records imported: ' || COUNT(*) FROM insurance_temp;
EOF

echo "✅ Insurance data imported to temp table"

echo ""
echo "🔄 Step 2: Merging data (this will take several minutes)..."

# Perform the merge - only records that exist in both databases
sqlite3 "$TARGET_DB" <<EOF
-- Optimize for merge operation
PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;
PRAGMA cache_size = 100000;
PRAGMA temp_store = MEMORY;

-- Perform the merge using INNER JOIN (only matching records)
INSERT INTO carriers_merged (
    -- DOT columns
    MCS150_DATE, ADD_DATE, STATUS_CODE, DOT_NUMBER, DUN_BRADSTREET_NO,
    PHY_OMC_REGION, SAFETY_INV_TERR, CARRIER_OPERATION, BUSINESS_ORG_ID, MCS150_MILEAGE,
    MCS150_MILEAGE_YEAR, MCS151_MILEAGE, TOTAL_CARS, MCS150_UPDATE_CODE_ID, PRIOR_REVOKE_FLAG,
    PRIOR_REVOKE_DOT_NUMBER, PHONE, FAX, CELL_PHONE, COMPANY_OFFICER_1,
    COMPANY_OFFICER_2, BUSINESS_ORG_DESC, TRUCK_UNITS, POWER_UNITS, BUS_UNITS,
    FLEETSIZE, REVIEW_ID, RECORDABLE_CRASH_RATE, MAIL_NATIONALITY_INDICATOR, PHY_NATIONALITY_INDICATOR,
    PHY_BARRIO, MAIL_BARRIO, CARSHIP, DOCKET1PREFIX, DOCKET1,
    DOCKET2PREFIX, DOCKET2, DOCKET3PREFIX, DOCKET3, POINTNUM,
    TOTAL_INTRASTATE_DRIVERS, MCSIPSTEP, MCSIPDATE, HM_Ind, INTERSTATE_BEYOND_100_MILES,
    INTERSTATE_WITHIN_100_MILES, INTRASTATE_BEYOND_100_MILES, INTRASTATE_WITHIN_100_MILES, TOTAL_CDL, TOTAL_DRIVERS,
    AVG_DRIVERS_LEASED_PER_MONTH, CLASSDEF, LEGAL_NAME, DBA_NAME, PHY_STREET,
    PHY_CITY, PHY_COUNTRY, PHY_STATE, PHY_ZIP, PHY_CNTY,
    CARRIER_MAILING_STREET, CARRIER_MAILING_STATE, CARRIER_MAILING_CITY, CARRIER_MAILING_COUNTRY, CARRIER_MAILING_ZIP,
    CARRIER_MAILING_CNTY, CARRIER_MAILING_UND_DATE, DRIVER_INTER_TOTAL, EMAIL_ADDRESS, REVIEW_TYPE,
    REVIEW_DATE, SAFETY_RATING, SAFETY_RATING_DATE, UNDELIV_PHY, CRGO_GENFREIGHT,
    CRGO_HOUSEHOLD, CRGO_METALSHEET, CRGO_MOTOVEH, CRGO_DRIVETOW, CRGO_LOGPOLE,
    CRGO_BLDGMAT, CRGO_MOBILEHOME, CRGO_MACHLRG, CRGO_PRODUCE, CRGO_LIQGAS,
    CRGO_INTERMODAL, CRGO_PASSENGERS, CRGO_OILFIELD, CRGO_LIVESTOCK, CRGO_GRAINFEED,
    CRGO_COALCOKE, CRGO_MEAT, CRGO_GARBAGE, CRGO_USMAIL, CRGO_CHEM,
    CRGO_DRYBULK, CRGO_COLDFOOD, CRGO_BEVERAGES, CRGO_PAPERPROD, CRGO_UTILITY,
    CRGO_FARMSUPP, CRGO_CONSTRUCT, CRGO_WATERWELL, CRGO_CARGOOTHR, CRGO_CARGOOTHR_DESC,
    OWNTRUCK, OWNTRACT, OWNTRAIL, OWNCOACH, OWNSCHOOL_1_8,
    OWNSCHOOL_9_15, OWNSCHOOL_16, OWNBUS_16, OWNVAN_1_8, OWNVAN_9_15,
    OWNLIMO_1_8, OWNLIMO_9_15, OWNLIMO_16, TRMTRUCK, TRMTRACT,
    TRMTRAIL, TRMCOACH, TRMSCHOOL_1_8, TRMSCHOOL_9_15, TRMSCHOOL_16,
    TRMBUS_16, TRMVAN_1_8, TRMVAN_9_15, TRMLIMO_1_8, TRMLIMO_9_15,
    TRMLIMO_16, TRPTRUCK, TRPTRACT, TRPTRAIL, TRPCOACH,
    TRPSCHOOL_1_8, TRPSCHOOL_9_15, TRPSCHOOL_16, TRPBUS_16, TRPVAN_1_8,
    TRPVAN_9_15, TRPLIMO_1_8, TRPLIMO_9_15, TRPLIMO_16, DOCKET1_STATUS_CODE,
    DOCKET2_STATUS_CODE, DOCKET3_STATUS_CODE,

    -- Insurance columns
    MC_NUMBER, FORM_CODE, COVERAGE_TYPE, INSURANCE_COMPANY, POLICY_NUMBER,
    POLICY_EFFECTIVE_DATE, UNKNOWN_FLAG, COVERAGE_AMOUNT, POLICY_END_DATE, POLICY_CANCELLATION_DATE
)
SELECT
    -- DOT data from carriers
    c.MCS150_DATE, c.ADD_DATE, c.STATUS_CODE, c.DOT_NUMBER, c.DUN_BRADSTREET_NO,
    c.PHY_OMC_REGION, c.SAFETY_INV_TERR, c.CARRIER_OPERATION, c.BUSINESS_ORG_ID, c.MCS150_MILEAGE,
    c.MCS150_MILEAGE_YEAR, c.MCS151_MILEAGE, c.TOTAL_CARS, c.MCS150_UPDATE_CODE_ID, c.PRIOR_REVOKE_FLAG,
    c.PRIOR_REVOKE_DOT_NUMBER, c.PHONE, c.FAX, c.CELL_PHONE, c.COMPANY_OFFICER_1,
    c.COMPANY_OFFICER_2, c.BUSINESS_ORG_DESC, c.TRUCK_UNITS, c.POWER_UNITS, c.BUS_UNITS,
    c.FLEETSIZE, c.REVIEW_ID, c.RECORDABLE_CRASH_RATE, c.MAIL_NATIONALITY_INDICATOR, c.PHY_NATIONALITY_INDICATOR,
    c.PHY_BARRIO, c.MAIL_BARRIO, c.CARSHIP, c.DOCKET1PREFIX, c.DOCKET1,
    c.DOCKET2PREFIX, c.DOCKET2, c.DOCKET3PREFIX, c.DOCKET3, c.POINTNUM,
    c.TOTAL_INTRASTATE_DRIVERS, c.MCSIPSTEP, c.MCSIPDATE, c.HM_Ind, c.INTERSTATE_BEYOND_100_MILES,
    c.INTERSTATE_WITHIN_100_MILES, c.INTRASTATE_BEYOND_100_MILES, c.INTRASTATE_WITHIN_100_MILES, c.TOTAL_CDL, c.TOTAL_DRIVERS,
    c.AVG_DRIVERS_LEASED_PER_MONTH, c.CLASSDEF, c.LEGAL_NAME, c.DBA_NAME, c.PHY_STREET,
    c.PHY_CITY, c.PHY_COUNTRY, c.PHY_STATE, c.PHY_ZIP, c.PHY_CNTY,
    c.CARRIER_MAILING_STREET, c.CARRIER_MAILING_STATE, c.CARRIER_MAILING_CITY, c.CARRIER_MAILING_COUNTRY, c.CARRIER_MAILING_ZIP,
    c.CARRIER_MAILING_CNTY, c.CARRIER_MAILING_UND_DATE, c.DRIVER_INTER_TOTAL, c.EMAIL_ADDRESS, c.REVIEW_TYPE,
    c.REVIEW_DATE, c.SAFETY_RATING, c.SAFETY_RATING_DATE, c.UNDELIV_PHY, c.CRGO_GENFREIGHT,
    c.CRGO_HOUSEHOLD, c.CRGO_METALSHEET, c.CRGO_MOTOVEH, c.CRGO_DRIVETOW, c.CRGO_LOGPOLE,
    c.CRGO_BLDGMAT, c.CRGO_MOBILEHOME, c.CRGO_MACHLRG, c.CRGO_PRODUCE, c.CRGO_LIQGAS,
    c.CRGO_INTERMODAL, c.CRGO_PASSENGERS, c.CRGO_OILFIELD, c.CRGO_LIVESTOCK, c.CRGO_GRAINFEED,
    c.CRGO_COALCOKE, c.CRGO_MEAT, c.CRGO_GARBAGE, c.CRGO_USMAIL, c.CRGO_CHEM,
    c.CRGO_DRYBULK, c.CRGO_COLDFOOD, c.CRGO_BEVERAGES, c.CRGO_PAPERPROD, c.CRGO_UTILITY,
    c.CRGO_FARMSUPP, c.CRGO_CONSTRUCT, c.CRGO_WATERWELL, c.CRGO_CARGOOTHR, c.CRGO_CARGOOTHR_DESC,
    c.OWNTRUCK, c.OWNTRACT, c.OWNTRAIL, c.OWNCOACH, c.OWNSCHOOL_1_8,
    c.OWNSCHOOL_9_15, c.OWNSCHOOL_16, c.OWNBUS_16, c.OWNVAN_1_8, c.OWNVAN_9_15,
    c.OWNLIMO_1_8, c.OWNLIMO_9_15, c.OWNLIMO_16, c.TRMTRUCK, c.TRMTRACT,
    c.TRMTRAIL, c.TRMCOACH, c.TRMSCHOOL_1_8, c.TRMSCHOOL_9_15, c.TRMSCHOOL_16,
    c.TRMBUS_16, c.TRMVAN_1_8, c.TRMVAN_9_15, c.TRMLIMO_1_8, c.TRMLIMO_9_15,
    c.TRMLIMO_16, c.TRPTRUCK, c.TRPTRACT, c.TRPTRAIL, c.TRPCOACH,
    c.TRPSCHOOL_1_8, c.TRPSCHOOL_9_15, c.TRPSCHOOL_16, c.TRPBUS_16, c.TRPVAN_1_8,
    c.TRPVAN_9_15, c.TRPLIMO_1_8, c.TRPLIMO_9_15, c.TRPLIMO_16, c.DOCKET1_STATUS_CODE,
    c.DOCKET2_STATUS_CODE, c.DOCKET3_STATUS_CODE,

    -- Insurance data
    i.MC_NUMBER, i.FORM_CODE, i.COVERAGE_TYPE, i.INSURANCE_COMPANY, i.POLICY_NUMBER,
    i.POLICY_EFFECTIVE_DATE, i.UNKNOWN_FLAG, i.COVERAGE_AMOUNT, i.POLICY_END_DATE, i.POLICY_CANCELLATION_DATE

FROM insurance_temp i
INNER JOIN (SELECT * FROM "$DOT_DB".carriers) c ON CAST(i.DOT_NUMBER AS INTEGER) = c.DOT_NUMBER;

-- Get final count
SELECT 'Records successfully merged: ' || COUNT(*) FROM carriers_merged;

-- Clean up
DROP TABLE insurance_temp;
EOF

echo ""
echo "✅ Merge completed!"

echo ""
echo "📊 DB-V3 Summary:"
sqlite3 "$TARGET_DB" "
SELECT 'Total merged records: ' || COUNT(*) FROM carriers_merged;
SELECT 'Records with insurance: ' || COUNT(*) FROM carriers_merged WHERE MC_NUMBER IS NOT NULL;
SELECT 'Records with phone: ' || COUNT(*) FROM carriers_merged WHERE PHONE IS NOT NULL;
SELECT 'Records with email: ' || COUNT(*) FROM carriers_merged WHERE EMAIL_ADDRESS IS NOT NULL;"

echo ""
echo "🏆 Top 5 states in merged database:"
sqlite3 "$TARGET_DB" "SELECT PHY_STATE, COUNT(*) as count FROM carriers_merged WHERE PHY_STATE IS NOT NULL GROUP BY PHY_STATE ORDER BY count DESC LIMIT 5;"

echo ""
echo "🎯 DB-V3 MERGE COMPLETE!"
echo "📁 Database: $TARGET_DB"
ls -lh "$TARGET_DB"